### PR TITLE
Fix/searchundoredo

### LINKED ISSUE #171: Redo does not work after Undo
After attempting a lot of operation of addition, edition, done and undo multiple times.
Next redo throw an error: `Too many argument`

### LINKED ISSUE #183: bug / deleting tasks in search result
Those deleted remains in the list making the search result indexing messed up.

### PR DESCRIPTION
**Pull request by starkipraggy**
Closes #183, closes #171 

- [X] Search page shows all tasks by default
- [X] Search page now refreshes after every operation
- [X] Redo bug fixed

### CODE REVIEW

File: DoLah/Models/CalendarInverter.cpp [hunk 1]
```diff
@@ -11,11 +11,12 @@ void DoLah::CalendarInverter::invertAdd(AbstractTask * task, Calendar * calendar
 }
 
 void DoLah::CalendarInverter::invertDelete(AbstractTask * task, Calendar * calendar){
-    calendar->addTask(task, task->getIndex());
+    //calendar->addTask(task, task->getIndex());
```
Comment (bsmmoon) [inline DoLah/Models/CalendarInverter.cpp]: Commented code.

I'll remove it and merge the branch.

**Comment by 9gix** [comment]
@starkipraggy  Please fix the search behavior mentioned in #201 before making a new PR.

**Comment by 9gix** [comment]
Reopen #171 since this PR is reverted. Please close the issue after the next merge.
